fix: scala and fasterxml collision
 com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.17.2 requires Jackson Databind version >= 2.17.0 and < 2.18.0 - Found jackson-databind version 2.18.2